### ISSUE TITLE
new content not always copied

### ISSUE THREAD

**Issue by atomGit** [hnakamur/FormatLink-Firefox#38]
related: #18 

Firefox v78-79

once in a while the content is not copied to the clipboard

**Comment by atomGit** [comment]
it looks like the content is always copied as long as one pauses slightly after the copy - this causes me to wonder if the copied content is perhaps not added to the clipboard as early as possible

**Comment by hnakamur** [comment]
I see this problem too, but I don't know what to do since I cannot think of a way to detect the copy was successful or not.
As a workaround, it might be good to show popup/toast on the content page after copying, but I don't know if it is actually useful or not.

I'm sorry but I don't have time right now since I'm busy with other things to do.
Maybe I'm going to investigate this issue when I have free time.

**Comment by atomGit** [comment]
i'm not seeing this problem any longer
